/****************************************************************************
| Program name : 13_final data set
| Date (update):
| Project name :
| Purpose      :
|
|
****************************************************************************/

data oac_can.final_cohort;
	merge oac_can.cohort_v13(in=in1) oac_can.Outcome_summary_2(keep=patient_id switch_drug_class switch_date time_init_switch);
	by patient_id;
	label patient_id = "Patient ID"
		  AKF = "Renal disease"
		  ALF = "Liver disease"
		  CHF = "Congestive heart failure"
		  COPD = "Chronic obstructive pulmonary disease"
		  CR = "Coronary revascularization"
		  DOB = "Date of birth"
		  Dia = "Diabetes mellitus"
		  Dualflag = "Medicaid eligibility"
		  HL = "Hyperlipidemia"
		  HT = "Hypertension"
		  IA = "Inflammatory artritis"
		  Maritalm = "Marital status"
		  Other_CD = "Other ischemic heart disease"
		  Other_IHD = "Other cerebrovascular disease"
		  PUD = "Peptic ulcer disease"
		  Racem = "Race/ethnicity"
		  Regionm = "Census region"
		  STT = "Stroke, TIA, thromboembolism history"
		  VD = "Vascular disease history (prior MI, peripheral artery disease, or aortic plaque)"
		  acei = "Angiotensin-converting enzyme inhibitors"
		  afib_mon = "Index date month" 
		  afib_year = "Index date year"
		  age = "age at index date"
		  age_grp = "age group"
		  alcohol = "Alcoholism"
		  anemia = "Anemia"
		  antiarrhythmics = "Antiarrhythmics"
		  antiplatelets = "Antiplatelets"
		  arb = "Angiotensin-receptor blockers"
		  aspirin = "Aspirin"
		  asthma = "Asthma"
		  av = "Antiangina vasodilators"
		  bb = "Beta-Blockers"
		  bleed = "Prior major bleeding or predisposition to bleeding"
		  cancer_date = "Cancer diagnosis date"
		  cancer_type = "Cancer type"
		  ccb = "Calcium-channel blockers"
		  chemo = "Receipt of hemotherapy"
		  cv_score = "CHA?DS?-VASc Score"
		  dd = "Diabetes drugs"
		  statins = "Statins"
		  dementia = "Dementia"
		  diuretics = "Diuretics"
		  estrogens = "Estrogens"
		  gout = "Gout"
		  hb_score = "HAS-Bled score"
		  hlmwh = "Heparin and low-molecular-weight heparins"
		  naid = "Nonsteroidal anti-inflammatory drugs"
		  nlld = "Nonstatin lipid-lowering drugs"
		  number_prior_hospitalization = "Prior hospitalizations"
		  number_prior_physician = "Prior physician visits"
		  oa = "Other antihypertensives"
		  ppi = "Proton-pump inhibitors"
		  progestins = "Progestins"
		  stage = "Cancer stage"
		  tumor_size = "Cancer size"
		  grade = "Cancer grade"
		  death_date = "Date of Death"
		  death_date_v1 = "Updated date of death after accounting for study end date"
		  death_year = "Death date year"
		  death_year_v1 = "Updated death date year after accounting for study end date"
		  edu = "Zip code percent persons with >=12 year education"
		  index_date = "index date (First NVAF diagnosis date)"
		  init_date = "First prescription date of warfarin or direct oral anticoagulants (dabigatran, rivaroxaban, apixaban and edoxaban)"
		  init_drug_class = "Initiated warfarin or DOAC"
		  init_oac = "Flag for initiated OAC or not"
		  init_year = "OAC initiation year"
		  rank_edu_char = "quartile categories for education"
		  rank_income_char = "quartile categories for per capita income"
		  study_end_date = "Study ends at Dec 31 2016"
		  switch_date = "Among patients who initiated warfarin, first switch date to direct oral anticoagulants; among patients who initiated direct oral anticoagulants, first switch date to warfarin"
		  switch_drug_class = "Switched to warfarin or DOAC"
		  time_afib_death = "Month difference between index date and death date"
		  time_afib_init = "Month difference between index date and initiation date"
		  time_afib_init_v1 = "Time from index date to initiation date in month categories"
		  time_afib_to_oac = "Time from index date to initiation date"
		  time_cancer_to_afib = "Time from cancer diagnosis date to index date"
		  time_init_switch = "Month difference between initation date and switch date"
		  ;

run;

proc contents data=oac_can.final_cohort;
run;
